export const fallbackMenuItems = [
  {
    id: 'fallback-pani-puri',
    category: 'Street Food & Snacks',
    name: 'Pani Puri',
    description: 'Crispy hollow puris filled with spicy tangy water and potato mash.',
    priceRupees: 30,
    imagePath: '/img/panipuri.png',
  },
  {
    id: 'fallback-mix-chaat',
    category: 'Street Food & Snacks',
    name: 'Mix Chaat',
    description: 'A delightful mix of crispy papdi, boiled potatoes, chickpeas, yogurt and chutneys.',
    priceRupees: 30,
    imagePath: '/img/mix_chaat.png',
  },
  {
    id: 'fallback-veg-momos',
    category: 'Street Food & Snacks',
    name: 'Veg Momos',
    description: 'Steamed dumplings filled with savory mixed vegetable filling, served with fiery red chutney.',
    priceRupees: 50,
    imagePath: '/img/momo.png',
  },
  {
    id: 'fallback-chicken-momos',
    category: 'Street Food & Snacks',
    name: 'Chicken Momos',
    description: 'Steamed dumplings filled with savory minced chicken filling, served with fiery red chutney.',
    priceRupees: 60,
    imagePath: '/img/momo.png',
  },
  {
    id: 'fallback-french-fries',
    category: 'Street Food & Snacks',
    name: 'French Fries',
    description: 'Crispy golden potato fries seasoned with salt and spices.',
    priceRupees: 70,
    imagePath: '/img/french_fries.png',
  },
  {
    id: 'fallback-chicken-biryani',
    category: 'Mains',
    name: 'Chicken Biryani',
    description: 'Aromatic basmati rice cooked with tender meat, spices, and herbs.',
    priceRupees: 120,
    imagePath: '/img/biryani.png',
  },
  {
    id: 'fallback-veg-biryani',
    category: 'Mains',
    name: 'Veg Biryani',
    description: 'Aromatic basmati rice cooked with mixed vegetables, spices, and herbs.',
    priceRupees: 100,
    imagePath: '/img/biryani.png',
  },
  {
    id: 'fallback-masala-dosa',
    category: 'Mains',
    name: 'Masala Dosa',
    description: 'Crispy, golden-brown fermented rice crepe served with savory sambar and fresh coconut chutney.',
    priceRupees: 60,
    imagePath: '/img/dosa.png',
  },
  {
    id: 'fallback-margherita-pizza',
    category: 'Mains',
    name: 'Margherita Pizza',
    description: 'Classic pizza with fresh tomato sauce, mozzarella cheese, and basil.',
    priceRupees: 120,
    imagePath: '/img/margherita_pizza.png',
  },
  {
    id: 'fallback-gourmet-burger',
    category: 'Mains',
    name: 'Gourmet Burger',
    description: 'Juicy patty inside a toasted bun with fresh lettuce, tomatoes, and cheese.',
    priceRupees: 90,
    imagePath: '/img/gourmet_burger.png',
  },
  {
    id: 'fallback-masala-cola',
    category: 'Drinks & Beverages',
    name: 'Masala Cola',
    description: 'Chilled cola infused with roasted cumin, black salt, and spices.',
    priceRupees: 50,
    imagePath: '/img/masala_cola.png',
  },
  {
    id: 'fallback-sweet-lassi',
    category: 'Drinks & Beverages',
    name: 'Sweet Lassi',
    description: 'Thick, creamy yogurt drink sweetened and garnished with dry fruits.',
    priceRupees: 60,
    imagePath: '/img/sweet_lassi.png',
  },
  {
    id: 'fallback-nimbu-pani',
    category: 'Drinks & Beverages',
    name: 'Nimbu Pani',
    description: 'Refreshing Indian lemonade made with fresh lemon juice and a hint of salt and sugar.',
    priceRupees: 30,
    imagePath: '/img/nimbu_pani.png',
  },
  {
    id: 'fallback-cold-drink',
    category: 'Drinks & Beverages',
    name: 'Cold Drink',
    description: 'Chilled carbonated beverage of your choice.',
    priceRupees: 30,
    imagePath: '/img/colddrink.png',
  },
  {
    id: 'fallback-rose-falooda',
    category: 'Desserts',
    name: 'Rose Falooda',
    description: 'A rich dessert drink with rose syrup, vermicelli, sweet basil seeds, and ice cream.',
    priceRupees: 100,
    imagePath: '/img/rose_falooda.png',
  },
  {
    id: 'fallback-ice-cream',
    category: 'Desserts',
    name: 'Ice Cream',
    description: 'A couple scoops of delicious frozen dessert.',
    priceRupees: 50,
    imagePath: '/img/icecream.png',
  },
];
